### ISSUE TITLE
我想加入，虽然我我只有周日晚上有空…

### ISSUE THREAD

**Issue by bcmRayCrazy-coder** [PupilStudio/XTCClassTime#3]
我会html python js css ，cs cpp还在自学，加我Q975875040，我六年级也没什么时间，包容一下，主要做网站，例子：[点这里丫，是用的免费二级域名qwq](http://bcmraycrazy.byethost11.com/) 
![DAC2F1B6-133A-4C2F-A71F-6B1E7476739C](https://user-images.githubusercontent.com/65066644/96874087-5058f300-14a8-11eb-8a58-28a2e4d6f78b.jpeg)
—我们班同学的痛苦面具

**Comment by PupilStudio** [comment]
说得好，但我为什么要加你好友（
“重要提醒：目前源文件缺失，暂时无法正常显示”，并且需要挂梯子
真不错，痛苦面具真不错，不过请注意隐私安全
**别学C#! 别学C#!! 别学C#!!!**
Java/Kotlin 请

**Comment by nonusx** [comment]
![image](https://user-images.githubusercontent.com/60562136/100421684-d24dc480-30c3-11eb-824b-d5597fd5133b.png)

**Comment by nonusx** [comment]
第一次看到用c#写android的
